Took 118 skeleton animations
afraidofdark/ToolKit pull request #118
Opened 2022-08-03 14:12 UTC by fcturan20

Skeleton system system is implemented

2022-08-03 19:07 UTC, afraidofdark requested changes

2022-08-03 19:07 UTC, afraidofdark commented on ToolKit/Skeleton.cpp
> +        childsOfParent.erase(childsOfParent.begin() + childIndx);
You can't delete entries in  a for loop. You are invalidating the iterator ! FIX IT !

2022-08-03 19:07 UTC, afraidofdark commented on ToolKit/Skeleton.cpp
> +        childsOfParent.erase(childsOfParent.begin() + childIndx);
https://www.techiedelight.com/remove-elements-vector-inside-loop-cpp/

2022-08-03 19:07 UTC, afraidofdark commented on ToolKit/Skeleton.cpp
> +  void Skeleton::UnInit()
a space please

2022-08-03 19:07 UTC, afraidofdark commented on ToolKit/Skeleton.cpp
> +    auto writeTransformFnc =
Nice candidate to be moved to Util.h Xml related section

2022-08-03 19:07 UTC, afraidofdark commented on ToolKit/Skeleton.cpp
> +    boneXmlNode->append_attribute
I believe you can use WriteAttr

2022-08-03 19:15 UTC, fcturan20 commented on ToolKit/Mesh.cpp
> +    for (const auto& v : mesh->m_clientSideVertices)
Vertex type isn't known; either Vertex or SkinVertex. I don't want to add any other template argument that function already can solve internally.

2022-08-03 19:20 UTC, fcturan20 commented on ToolKit/Mesh.cpp
> +        writeMesh(doc, container, static_cast<const SkinMesh*>(m));
It's not possible because writeMesh is a template but variable type information is dynamic (inheritance). Vertex-SkinVertex is the reason why writeMesh is template.

2022-08-03 19:24 UTC, fcturan20 commented on ToolKit/Mesh.cpp
> +  void SkinMesh::ConstructFaces()
It's the same function but they access to different m_clientSideVertices. Because SkinMesh has 2 m_clientSideVertices vectors (one from Mesh base class (Vertex vector), one from derived class (SkinVertex vector)). SkinMesh::Init() was crashing because m_clientSideVertices was colliding in Mesh::ConstrucFaces(). 
This was a hot-fix. I guess can turn it into a template which can help.

2022-08-03 22:39 UTC, fcturan20 commented on ToolKit/Skeleton.cpp
> +    for (uint childIndx = 0; childIndx < childsOfParent.size(); childIndx++)
No, there isn't.

2022-08-04 10:33 UTC, afraidofdark approved these changes

2022-08-04 10:33 UTC, afraidofdark commented on Editor/App.cpp
> +      #ifndef TK_SAMPLE_SCENE
remove this please

2022-08-04 10:33 UTC, afraidofdark commented on Editor/App.cpp
> +    AnimRecord knightRunAnimRecord;
remove these variables

2022-08-04 17:14 UTC, merged