Dev/took 179
afraidofdark/ToolKit pull request #123
Opened 2022-08-09 14:30 UTC by Osman-Fatih-Cakir

2022-08-09 15:24 UTC, afraidofdark requested changes

2022-08-09 15:24 UTC, afraidofdark commented on ToolKit/FileManager.h
> +  struct FileSettings
do you mean image file settings ? or is this a generic struct ?
Naming is misleading

2022-08-09 15:24 UTC, afraidofdark commented on ToolKit/FileManager.h
> +      const String& filePath,
we have a struct that you define above for the inputs for this function

2022-08-09 15:24 UTC, afraidofdark commented on ToolKit/FileManager.h
> +  typedef std::variant
Instead of this complicated structure, you can return 2 things.
1) Xml data
2) Binary data
Each function that request the data, hopefully knows what the content is for the binary case.

2022-08-09 15:44 UTC, afraidofdark commented on ToolKit/FileManager.h
> +    FileDataType GetFile(FileType fileType, FileSettings& fileSettings);
You can further simplyfy this functin by just returning byte data. Since its internally used, you know what to do with the data. And either move the variant, filetype, filesettings declerations to cpp or hide them in the class as private members.

2022-08-09 15:45 UTC, afraidofdark commented on ToolKit/FileManager.h
> +    FileDataType GetFile(FileType fileType, FileSettings& fileSettings);
If you ask me, all you need is byte*

2022-08-10 09:35 UTC, Osman-Fatih-Cakir commented on ToolKit/FileManager.h
> +      const String& filePath,
I was thinking to use the struct for internal usage

2022-08-10 09:37 UTC, Osman-Fatih-Cakir commented on ToolKit/FileManager.h
> +    FileDataType GetFile(FileType fileType, FileSettings& fileSettings);
When loading with stbi it already loads with uint8 data type. Instead of casting to byte first and casting again to uint8, could we return the data without casting?

2022-08-10 10:29 UTC, rbellek commented on ToolKit/FileManager.h
> +    FileDataType GetFile(FileType fileType, FileSettings& fileSettings);
Just casting has not effect on the data. However, if we want to combine all possible return values as a single representation (like void pointer in the ancient ages) byte pointer is the probably the best one. I personally prefer variant over this kind of single byte pointer representation because casting is not safe in this circumstance although this is a private function.

2022-08-10 10:35 UTC, rbellek commented on ToolKit/FileManager.h
> +    FileDataType GetFile(FileType fileType, FileSettings& fileSettings);
> When loading with stbi it already loads with uint8 data type. Instead of casting to byte first and casting again to uint8, could we return the data without casting?

I believe byte pointer is more generic so casting to byte pointer is more convenient. No gain over developer's perspective by the way.

2022-08-11 11:18 UTC, afraidofdark approved these changes

2022-08-11 12:11 UTC, merged