Dev/took 214
afraidofdark/ToolKit pull request #138
Opened 2022-08-19 10:48 UTC by Osman-Fatih-Cakir

2022-08-19 20:29 UTC, rbellek requested changes
Please fix duplicated code blocks.

2022-08-19 20:29 UTC, rbellek commented on Editor/EditorLight.cpp
> +      // Add gizmo meshes to mesh component
This code block seems duplicated. If it is the same code line:153 please create a function and move it to the base class.
The function name is obvious: "Add gizmo meshes to mesh component".

2022-08-19 20:29 UTC, rbellek commented on Editor/EditorLight.cpp
> +      // Add gizmo meshes to mesh component
This code block seems duplicated. If it is the same code line:153 please create a function and move it to the base class.
The function name is obvious: "Add gizmo meshes to mesh component".

2022-08-19 20:29 UTC, rbellek commented on Editor/EditorLight.cpp
> +      // Add gizmo meshes to mesh component
This code block seems duplicated. If it is the same code line:247 please create a function and move it to the base class.
The function name is obvious: "Add gizmo meshes to mesh component".

2022-08-20 07:42 UTC, afraidofdark approved these changes

2022-08-20 07:44 UTC, afraidofdark approved these changes

2022-08-20 07:45 UTC, merged