Camera Focus
afraidofdark/ToolKit pull request #235
Opened 2022-10-31 11:32 UTC by Osman-Fatih-Cakir

2022-10-31 15:47 UTC, afraidofdark requested changes

2022-10-31 15:47 UTC, afraidofdark commented on ToolKit/Camera.h
> +    void FocusBoundingBox(const BoundingBox& bb);
Function name is vastly different than its description.
Change the name to FitFrustumToSphere
Add convert safety margin as a variable %10 marigin thing.
move reference link on top of the function implementation
Move it to geometry utis
Than use that utility function here in the camera class.
Also please document functions with proper formating

2022-10-31 15:47 UTC, afraidofdark commented on Editor/App.cpp
> +      m_focus         = true;
Why are we caching these variables, why not just call this function when the F key pressed ?

2022-11-02 09:57 UTC, Osman-Fatih-Cakir commented on Editor/App.cpp
> +      m_focus         = true;
This function is called from Window::ModShortCutSignals(const IntArray& mask) function which does not know about the current viewport.

With this function we can focus to the object for all 3d viewports.

2022-11-02 16:16 UTC, afraidofdark approved these changes

2022-11-02 16:21 UTC, merged