Dev/took 31
afraidofdark/ToolKit pull request #31
Opened 2022-04-16 13:30 UTC by Osman-Fatih-Cakir

2022-04-16 15:10 UTC, afraidofdark approved these changes

2022-04-16 15:10 UTC, afraidofdark commented on Editor/Mod.cpp
> +      if (n == 0)
why code gets here ? are we hiding a problem ?

2022-04-16 15:10 UTC, afraidofdark commented on Editor/Mod.cpp
> +        (
fix indentation please

2022-04-16 15:10 UTC, afraidofdark commented on Editor/UI.cpp
> +    TexturePtr UI::m_lockedIcon;
there is a lock icon already, why not use it ? If they are identical use only one icon please.

2022-04-16 15:10 UTC, afraidofdark commented on Editor/UI.cpp
> +        0
why is there 0 here ?

2022-04-16 15:10 UTC, afraidofdark commented on Editor/UI.cpp
> +        if
fix this and fallowing indentation problems. Did you auto indent ? and are you using 2 space for tabs.

2022-04-16 15:11 UTC, afraidofdark requested changes
there are thins you need to do mostly indentation problems

2022-04-16 17:44 UTC, Osman-Fatih-Cakir commented on Editor/Mod.cpp
> +      if (n == 0)
Since there is no actions to take (n=0) no need go. Also below code crashes when n is 0.

2022-04-17 10:09 UTC, afraidofdark approved these changes

2022-04-17 10:09 UTC, merged