Dev/engine/took 24 UI code refactor
afraidofdark/ToolKit pull request #35
Opened 2022-04-19 17:44 UTC by wotanfinrod

2022-04-19 18:03 UTC, afraidofdark commented on Source/UIManager.cpp
> +			UpdateSurfaces(vp);
Why update surface within render ? 
They should be seperated like
Update()
Render()

2022-04-19 18:27 UTC, afraidofdark requested changes

2022-04-19 18:27 UTC, afraidofdark commented on Source/UIManager.cpp
> +				m_childLayers.erase(it);
Erasing in for - while loops should use std::erase(std::remove_if()) structure or
https://www.techiedelight.com/remove-elements-vector-inside-loop-cpp/

You are safe because after the erase you are exiting from the function but if you try to use the iterator, code would broke the execution or worse, undefined behaivour.

2022-04-21 09:47 UTC, afraidofdark commented on ToolKit.sln
> +Project("{8BC9CEB8-8B4A-11D0-8D11-00A0C91BC942}") = "ThiefGo", "..\Go2\ThiefGo\Codes\build\ThiefGo.vcxproj", "{12540CC6-D96C-37CD-A2E1-5E08550C401F}"
DELETE THIS PROJECT !

2022-04-21 11:46 UTC, wotanfinrod commented on Source/UIManager.cpp
> +			UpdateSurfaces(vp);
Surface Update is in UILayer::Update now.

2022-04-22 16:22 UTC, afraidofdark approved these changes

2022-04-22 16:22 UTC, merged